- part2/command-model.md
typo fixed in last sentence of chapter "Aggregate implementations"
> typo fixed in "Aggregate implementations"

- part4/advanced-customizations.md
Include documentation on necessary impls, files, and includes an example with explanations
> Add handler enhancer documentation

- part-ii-domain-logic/testing.md
> AggregateTestFixture limitation.

- part-iii-infrastructure-components/spring-boot-autoconfiguration.md
> Added a chapter about blacklisting for spring cloud.

- part-iv-advanced-tuning/advanced-customizations.md
> Added Filtering Event Storage Engine chapter.

- part-i-getting-started/messaging-concepts.md
> Added Correlation Data Provider doc

- part-iii-infrastructure-components/spring-boot-autoconfiguration.md
> Added docs for defining a custom snapshot trigger definition and comm and target resolver

- book.json
- part-ii-domain-logic/command-model.md
- part-ii-domain-logic/event-handling.md
- part-ii-domain-logic/query-handling.md
- part-ii-domain-logic/sagas.md
- part-iii-infrastructure-components/event-processing.md
> Improved code examples

- part-ii-domain-logic/command-model.md
> Added event forwarding mode docs.

- part-iii-infrastructure-components/event-processing.md
> Added doc for EventTrackerStatus.

- book.json
- part-iv-advanced-tuning/advanced-customizations.md
> Doc about serializer configuration.

- part-iii-infrastructure-components/event-processing.md
> Added doc about Replay API.

- part-iii-infrastructure-components/event-processing.md
Documentation as described in #36
> Provided documentation for Kafka Producer and MessageSource.

- part-iii-infrastructure-components/repository-and-event-store.md
We have found that MongoDb does not seem to be the best fit in all situation for an EventStore.
This PR describes our doubts as a hint tied to the MongoDb section.
> Down tune MongoDb as a good fit the EventStore

- part-iii-infrastructure-components/event-processing.md
> [#50] Added details about custom tracking token position.

- part-iii-infrastructure-components/command-dispatching.md
> [#32] @CommandHandlerInterceptor doc.

- part-iii-infrastructure-components/query-processing.md
Improved description of Direct and Scatter-Gather queries.
Added description of Subscription query.
Resolves #29
> [#29] Three types of queries

- part-ii-domain-logic/command-model.md
> [#38] Added documentation about spawning new aggregate.

- part-iv-advanced-tuning/performance-tuning.md
> Added details about Filtering Snapshots.

- part-iv-advanced-tuning/advanced-customizations.md
> Handler(Enhancer)Definitions configuration.
